# Generated by Django 3.2.12 on 2022-11-15 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_models_help_text'),
        ('seed', '0205_email_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_emails', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='email',
            name='_property_views',
            field=models.ManyToManyField(related_name='_emails', to='seed.PropertyView'),
        ),
        migrations.AddField(
            model_name='email',
            name='_source_action',
            field=models.CharField(blank=True, help_text='Why was this email sent?', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='_source_page',
            field=models.IntegerField(blank=True, choices=[(0, 'BEAM'), (1, 'Script'), (2, 'Landing'), (3, 'Post Office'), (4, 'Helpdesk')], default=None, help_text='Where in BEAM was this email sent from?', null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='_taxlot_views',
            field=models.ManyToManyField(related_name='_emails', to='seed.TaxLotView'),
        ),
        migrations.AddField(
            model_name='email',
            name='_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_emails', to='helpdesk.ticket'),
        ),
        migrations.AddField(
            model_name='email',
            name='_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_email_templates', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='_tag_mappings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='_use_color_footer',
            field=models.BooleanField(blank=True, default=False, help_text='If this is checked, it will add the Orgs Color into the Email Footer', verbose_name='Use Org Color in Footer'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='_use_color_header',
            field=models.BooleanField(blank=True, default=False, help_text='If this is checked, it will add the Orgs Color into the Email Banner', verbose_name='Use Org Color in Header'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='_use_logo_header',
            field=models.BooleanField(blank=True, default=False, help_text='If this is checked, it will add the Logo into the Email Banner', verbose_name='Use Org Logo in Header'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='_use_name_footer',
            field=models.BooleanField(blank=True, default=False, help_text='If this is checked, it will add the Org name into the Email Footer', verbose_name='Use Org Name in Footer'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_email_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
