# Generated by Django 3.2.12 on 2022-11-15 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0207_delete_beam_postoffice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0075_forms_unlisted'),
        ('orgs', '0041_organization_bcc_enabled'),
        ('post_office', '0012_auto_20221115_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='_source_action',
            new_name='source_action',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='_source_page',
            new_name='source_page',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='_tag_mappings',
            new_name='tag_mappings',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='_use_color_footer',
            new_name='use_color_footer',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='_use_color_header',
            new_name='use_color_header',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='_use_logo_header',
            new_name='use_logo_header',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='_use_name_footer',
            new_name='use_name_footer',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='_organization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='_organization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='_property_views',
            new_name='property_views',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='_taxlot_views',
            new_name='taxlot_views',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='_ticket',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='_user',
            new_name='user',
        ),
    ]
