# Generated by Django 3.2.12 on 2022-11-15 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0207_delete_beam_postoffice'),
        ('helpdesk', '0075_forms_unlisted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0041_organization_bcc_enabled'),
        ('post_office', '0013_auto_20221115_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='email',
            name='property_views',
            field=models.ManyToManyField(related_name='emails', to='seed.PropertyView'),
        ),
        migrations.AlterField(
            model_name='email',
            name='taxlot_views',
            field=models.ManyToManyField(related_name='emails', to='seed.TaxLotView'),
        ),
        migrations.AlterField(
            model_name='email',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='helpdesk.ticket'),
        ),
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
